fix: small black block when there is no compositor
linuxdeepin/dde-tray-loader pull request #228
Opened 2024-12-20 08:18 UTC by tsic404

make x embed tray icon size to 1

log: as title

2024-12-31 02:34 UTC, zccrs requested changes

2024-12-31 02:34 UTC, zccrs commented on plugins/application-tray/util.cpp
> +QPoint Util::getMousePos() const
为什么不直接用 QCurosr::pos

2024-12-31 02:34 UTC, zccrs commented on plugins/application-tray/xcbthread.cpp
> +    : QThread(parent), m_connection(connection)
````
: QThread(parent)
, m_connection(connection)
````

2024-12-31 02:34 UTC, zccrs commented on plugins/application-tray/xcbthread.cpp
> +            }
对齐

2024-12-31 02:34 UTC, zccrs commented on plugins/application-tray/xcbthread.cpp
> +        free(event);
同上

2024-12-31 02:34 UTC, zccrs commented on plugins/application-tray/xcbthread.cpp
> +                UTIL->setX11WindowInputShape(lE->event, QSize(0, 0));
这个逻辑是什么意思，最好是加个注释

2024-12-31 02:34 UTC, zccrs commented on plugins/application-tray/util.cpp
> +    m_xcbThread = new XcbThread(m_x11connection);
`m_x11connection` 是独立于Qt自己创建的吗

2024-12-31 05:07 UTC, tsic404 commented on plugins/application-tray/util.cpp
> +QPoint Util::getMousePos() const
因为在dde-shell的合成器里面，QCurosr::pos返回的会是在dde-shell的位置。这儿需要拿到外面显示服务器的位置。

2024-12-31 05:08 UTC, tsic404 commented on plugins/application-tray/util.cpp
> +    m_xcbThread = new XcbThread(m_x11connection);
程序运行在dde-shell的合成器里面，默认没有xcb的链接，所以需要自己创建一个。

2025-01-02 06:05 UTC, zccrs commented
/+1

2025-01-17 06:41 UTC, tsic404 commented
/forcemerge

2025-01-17 06:41 UTC, merged